### PR TITLE
Feature/cleaner gui

### PR DESCRIPTION
**Pull request by forslund**
- Do not scroll the background when changing pages inside namespace
- Hide Status Indicator
- Hide Page indicator
- Hide Back Button

### CODE REVIEW

**Comment by notmart** [comment]
the back button comes from the older revision, so is pretty much dead code (should be removed rather than hidden), it will need something that does this action in some way, but will need to be designed i guess.

About removing the parallax of the background i guess a design discussion should happen.. I'm not married to that parallax thing, tough if removed the way the image is loaded and scaled/cropped should be a bit different

**Comment by forslund** [comment]
Points well made. I only hid these so things could be easily reverted.

**Comment by notmart** [comment]
I'll have to fix it then.
by actually removing that dead code and changing the background to use anchors which should simplify the code a bit

**Comment by notmart** [comment]
so, commit 1c74fe412a507 makes use of anchors and cropping in the image elements, which makes for more efficient code even tough same look

**Pull request merged**
