### PR TITLE
provide openSUSE Leap 15.x support

### PR DESCRIPTION
**Pull request by megamaced**
### How to use this template
Under each heading below is a short outline of the information required. When submitting a PR, please delete this text and replace it with your own. 

The CLA section can be deleted entirely.

#### Description
Provides openSUSE Leap 15.x support in install script

If needed follow up with as much detail as required.

#### Type of PR
If your PR fits more than one category, there is a high chance you should submit more than one PR. Please consider this carefully before opening the PR.
_Either delete those that do not apply, or add an x between the square brackets like so: `- [x]`_
- [ ] Bugfix
- [X ] Feature implementation
- [ ] Refactor of code (without functional changes)
- [ ] Documentation improvements
- [ ] Test improvements

#### Testing
How can someone reviewing this PR test that it is working properly? Is there appropriate test coverage for this change?

#### Documentation
Does documentation for this already exist? Are there docstrings on all the public methods you added or modified? Have these been updated?

#### CLA
To protect you, the project, and those who choose to use Mycroft technologies in systems they build, we ask all contributors to sign a Contributor License Agreement.

This agreement clarifies that you are granting a license to the Mycroft Project to freely use your work.  Additionally, it establishes that you retain the ownership of your contributed code and intellectual property.  As the owner, you are free to use your code in other work, obtain patents, or do anything else you choose with it.

If you haven't already signed the agreement and been added to our public [Contributors repo](https://github.com/mycroftAI/contributors) then please head to https://mycroft.ai/cla to initiate the signing process.

### CODE REVIEW

**Comment by krisgesling** [comment]
Thanks @megamaced, this looks pretty straight forward. 

I've just pinged our community to get a confirmation that the package list is everything that's required.

**Comment by forslund** [comment]
I have an openSuse VM, I can do a test during the weekend

**Comment by forslund** [comment]
Tested on fresh Leap install and it works well!

Maybe the line

`Enter choice [ 1 - 5 ]` should be updated...there are 8 choices now :)

**Comment by forslund** [comment]
Looks good now!

**Pull request merged**
