### PR TITLE
Fix mycroft-gui-core loader and stop

### PR DESCRIPTION
**Pull request by PureTryOut**
The conditional statement in the stop script was never actually closed

Also fix some shellcheck issues while we're at it

### CODE REVIEW

**Comment by forslund** [comment]
Nice catch! Should the exit be `exit 1` indicating an error?

**Comment by PureTryOut** [comment]
Yes, shellcheck mentions it and it's to make sure we exit in case cd'ing fails. E.g. the directory might for whatever reason not exist anymore and otherwise the `./stop-mycroft.sh` call would fail. Catching the cd itself resolves that.

**Comment by forslund** [comment]
Yeah I understand the reason, just thinking that instead of a bare exit (which returns 0 if I recall correctly) it should call with a non-zero code to indicate exit on failure

**Comment by PureTryOut** [comment]
Ah, yeah I guess so. Will change

**Comment by forslund** [comment]
Ah it uses the last exit code. I take it all back :)

**Comment by forslund** [comment]
It's fine as is. I was wrong

**Pull request merged**
